language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
install:
  - composer install

script:
  - phpunit --configuration phpunit.xml.dist --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
